-- Data generated by https://mockaroo.com

create table EMPLOYEE (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(10),
	job_title VARCHAR(100),
	avatar VARCHAR(200)
);